global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: flower
    static_configs:
      - targets: ["message_service_local_flower:5555"]
  - job_name: django
    static_configs:
      - targets: ["localhost:8000", "message_service_local_django:8000"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
