# Generated by Django 3.2.12 on 2022-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='client',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='text',
            field=models.CharField(max_length=250, null=True, verbose_name='Message Text'),
        ),
    ]
