# Generated by Django 3.2.12 on 2022-03-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20220321_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
