# Generated by Django 3.2.12 on 2022-03-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='clients',
            field=models.JSONField(null=True, verbose_name='Client List'),
        ),
    ]
