# Generated by Django 3.2.12 on 2022-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailinglist_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='send_time',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Send Time'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='clients',
            field=models.JSONField(null=True, verbose_name='Filter for Client List'),
        ),
    ]
